### ISSUE TITLE
Digest fails for some JAR files

### ISSUE THREAD

**Issue by maeichris** [threerings/getdown#103]
This problem happens under both ANT and the command line digester.

Sometimes when I've built JAR files, the digester will often/usually give an error on one of them.  If I re-run only the digester portion of the build on the same JAR files, it always errors on the same JAR file; if I re-build the JAR files first, then a different JAR will have the error.

Note: All the JAR files are signed when they're built, as I'm using the same JARs for the Java WebStart deployment and want to just drop in Getdown as a transitional method.

When executing the digester manually, I get the following exception stack trace (for different JARs in different builds):

```
Exception in thread "main" java.io.IOException: Error computing digest for: iText-2.1.7.js6.jar
        at com.threerings.getdown.data.f.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at sun.security.pkcs.SignerInfo.getTimestamp(SignerInfo.java:568)
        at sun.security.util.SignatureFileVerifier.getSigners(SignatureFileVerifier.java:722)
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:295)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
        at java.util.jar.JarVerifier.update(JarVerifier.java:230)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
        at java.util.jar.JarFile.getInputStream(JarFile.java:450)
        at com.threerings.getdown.data.Resource.computeDigest(Unknown Source)
        at com.threerings.getdown.data.Resource.computeDigest(Unknown Source)
        ... 4 more
```

Not being able to reliably create digests for the JAR files is a show stopper-level bug.

----

As a side request, in addition to finding out why it sometimes fails and sometimes doesn't, it would be nice if the error message within the ANT task contained additional information about the error's context.

When using the `<digest appdir="..."/>` ANT task, it will fail on some builds and not on others.

Here's the ant snippet:
```
	<taskdef name="digest" classname="com.threerings.getdown.tools.DigesterTask"
		classpath="${jar.repository}/dist/getdown/getdown-1.7.1.jar"/>
	<digest appdir="${getdown.staging.dir}"/>
```

Sometimes the build works fine, but more often it will give an error on any one of the 10 or so code= JAR files.  Here is an example of the error output:
```
   [digest] Generating digest file '/var/lib/jenkins/workspace/BuildFolder/SubProject/build/getdownstaging/digest.txt'...

BUILD FAILED
/var/lib/jenkins/workspace/BuildFolder/SubProject/build.xml:100: Error creating digest: Error computing digest for: CommonGui.jar
```

**Comment by samskivert** [comment]
I'm not sure what's going on with your jar files, but Getdown is just enumerating their contents and reading each entry. So I'm not sure what it could be doing to trigger that error. It seems far more likely that there is something weird about the jar files that is causing the internal jar handling code in the JDK to unexpectedly fail. As you can see from the stack trace, the failure is deep within the implementation code of the PKCS signature verification mechanism. There's nothing we can do to prevent the JDK code from failing while trying to read these jar files. I'm afraid you'll have to figure out what it is about these jar files that causes problems in the first place.

Have you tried different versions of the JDK? Are you able to unpack the signed jars with "jar xvf jarfile"? That would presumably use the same code that Getdown does to decode and read the contents of the jar files (assuming you're using the same JDK).

As for Ant not providing good feedback, we provide the underlying error, you just have to run "ant -v" (I think) to get Ant to show you the full error. That's just how Ant works, it's not something we can fix. I don't want to circumvent Ant's error reporting process. They have a "BuildException" that you're supposed to throw when something goes wrong, and you can fill in a cause exception, which we do. How Ant chooses to report that to the user is up to them.

**Comment by maeichris** [comment]
Thanks for the clear explanations, Michael!

I had tried unzip -v on the jar files, but not the jar command.  I re-enabled the digester in the build to try to reproduce the error and further investigate based on your suggestions.  However, I'm not currently getting the error.  That makes it a lot harder to track down.

Looking at the stack trace, it is using SignatureFileVerifier and calls SignerInfo.getTimestamp.  Our jar signing uses a timestamp authority, and I'm guessing these functions are having trouble with that aspect of reading the JAR.

Your logic about the error probably being outside of getdown makes sense.  If you don't mind leaving this ticket open up to another week, I'll continue the investigation once it begins repeating again and document in this ticket what I find (hopefully a solution!) in case other people come across the problem.

Regarding ant, I'm very sorry to have wasted your time on that.  If I knew at one time about how that option added the information in this kind of instance, I had forgotten; otherwise I somehow managed to have not learned it after all these years.

**Comment by maeichris** [comment]
The issue stopped happening for a few days, and then happened once again.  I've been working here and there when I have been able to steal away some time from my main project trying to figure out what the difference is, but I haven't come up with anything definitive yet.

I'm about to go on vacation for a few weeks.  I'll get back to this investigation when I'm back near the end of July.

**Comment by maeichris** [comment]
This is no longer a reproducible problem.  It appears to have been specific to certain releases of Java, but not with current versions.  There's no reason to keep this ticket open any longer.  If the problem occurs again, I'll open a new issue and link back to this one.
