### ISSUE TITLE
Proxy settings dialog references "the game"

### ISSUE THREAD

**Issue by haraldk** [threerings/getdown#105]
The proxy settings dialog that pops up when you launch an application without the correct proxy settings keep mentioning "the game" and "game data". 

![image](https://user-images.githubusercontent.com/110299/42378665-65a44a40-8128-11e8-8e45-0224cd4b34c2.png)

This is unfortunate, if you try to create a professional-looking application and not a game... 
Probably an easy fix in some language resource though.

Best regards,

-- 
Harald K

**Comment by samskivert** [comment]
I fixed the English translations. The word game was only used in that specific message.

I'm not qualified to fix the translations for other languages. If someone who knows these other languages wants to submit a PR for any of these other translation files (assuming they also use the word game), feel free:

https://github.com/threerings/getdown/tree/master/src/main/resources/com/threerings/getdown

**Comment by haraldk** [comment]
We're currently in the process of evaluating the library. 

If we chose use it, we'll likely submit a PR for one or two extra languages. :-)

-- 
Harald K

**Comment by ThomasGAI** [comment]
Hi,
since we are trying to replace WebStart with getdown, i created a PR with exact these requested changes in the messages_de.properties file. 

Greetings
Thomas G
