### ISSUE TITLE
Tracking fails due to URL-encoding

### ISSUE THREAD

**Issue by mrtnld** [threerings/getdown#107]
I'm trying to use GetDown and would like to use tracking.
But everytime I load my Application i get these errors:

> 2018/07/25 14:15:23:500 WARNING n$a.a: Invalid tracking URL [path=http://www.testing.com/, event=pct25, error=java.net.MalformedURLException: no protocol: http%3A//www.testing.com/pct25]

I have been looking through the code and found the method **encodePath** in **Application.java**
I think that to much is UTF8 encoded due to a change committed Feb 12, 2017.

A fix would be very welcome or perhaps a tip with at work-around.
:-)

**Comment by mrtnld** [comment]
I looked back in getdown-versions and have found that tracking works in verison 1.6

**Comment by samskivert** [comment]
Should be fixed in a886bca.
