### ISSUE TITLE
Empty "code" and "class" line neccessary in getdown.txt to show Icon

### ISSUE THREAD

**Issue by ThomasG-AI** [threerings/getdown#109]
Hi,

we created an installer for getdown which puts a dummy getdown.txt in the user directory. In this getdown.txt there is pretty much only the appbase and the ui.config in it. We discovered that the Icon is not showing on the first execution of getdown. Only afterwards when the "real" getdown.txt is downloaded from the server and getdown is started. 

The Icon is in the same directory as the getdown.txt and every other ui config works just fine(splash image etc.). What we found out is, that when you put an empty `class =`  and `code =` line into the dummy getdown.txt it works correctly. We think this is not really a desirable behaviour to expose such config properties when they are not needed in the first place. 

Is there a way to fix this on our side or does this need to be fixed in getdown itself?

Greetings
Thomas

**Comment by samskivert** [comment]
That's certainly weird behavior. I'll look into what is going on there. I agree it should not be necessary to put in empty `class =` and `code =` directives in the `getdown.txt` file.

**Comment by samskivert** [comment]
What platform are you seeing this behavior on? Windows?

**Comment by ThomasG-AI** [comment]
On Windows 10 yes
