### ISSUE TITLE
Allow configuration of MIN_EXIST_TIME

### ISSUE THREAD

**Issue by Adrodoc** [threerings/getdown#113]
Currently (in 1.7.1) the getdown GUI is open for at least 5 seconds. We would like it to close as soon as possible, so instead of using the constant `com.threerings.getdown.launcher.Getdown.MIN_EXIST_TIME` there should be a parameter for this in the getdown.txt file (which can default to 5 seconds).

**Comment by samskivert** [comment]
I added `ui.min_show_seconds` configuration, which will go out with the 1.7.2 release.

**Comment by Adrodoc** [comment]
Wouldn't it make more sense to use milliseconds to give the developers the maximal amount of control?

**Comment by Adrodoc** [comment]
I mean I am fine with seconds, but milliseconds is the usual time unit in programming so I think it makes sense to use it here. I can't imagine a use case for milliseconds either, but it doesn't hurt and is more flexible. I have never seen anything that makes use of nanoseconds. Also if you want to use nanoseconds you can no longer use Thread.sleep (or was there a nanosecond variant of Thread.sleep?)
