### ISSUE TITLE
GetDown usage and support

### ISSUE THREAD

**Issue by sreerama-naga** [threerings/getdown#114]
Hi,

we are looking to evaluate alternate for webstart.
It would be helpful if you share the any info/docs/links for GetDown, how to use, what are the operating systems it supports, features of it when compare with webstart and also how the support works.
thank you in advance!

Regards,
Sreeram

**Comment by samskivert** [comment]
Have you looked at the documentation page?

https://github.com/threerings/getdown/wiki

This is an open source project, created and maintained by volunteers. There's no "support" if you mean support as in the sense of commercial software. There's a mailing list and this documentation and a bunch of people who also use it and who are generally pretty helpful, but it would not be a good idea to use Getdown if you expect some sort of commercial software experience.
