### ISSUE TITLE
main class not found

### ISSUE THREAD

**Issue by singhGurpreetHsc** [threerings/getdown#116]
2018/08/14 12:16:39:609 INFO com.threerings.getdown: Dropping status 'm.validating'.
2018/08/14 12:16:39:619 INFO com.threerings.getdown: Attempting to refetch 'digest.txt' from 'http://localhost:8080/testPr/digest.txt'.
2018/08/14 12:16:39:634 WARNING com.threerings.getdown: Failed to refresh non-versioned digest: http://localhost:8080/testPr/digest.txt. Proceeding...
2018/08/14 12:16:39:640 INFO com.threerings.getdown: Verified resources [count=1, size=306k, duration=4ms]
2018/08/14 12:16:39:641 INFO com.threerings.getdown: Installing 0 downloaded resources:
2018/08/14 12:16:39:641 INFO com.threerings.getdown: Install completed.
2018/08/14 12:16:39:643 INFO com.threerings.getdown: Didn't find any custom environment variables, not setting any.
2018/08/14 12:16:39:643 INFO com.threerings.getdown: Running C:\Program Files\Java\jre1.8.0_51\bin\javaw.exe
  -classpath
  C:\Users\e01543\Downloads\getdown-master\target\app\application.jar
  -Dcom.threerings.getdown=true
  testPr.Abb
Error: Could not find or load main class testPr.Abb

**Comment by samskivert** [comment]
I don't know what advice to give you other than to be sure that your `application.jar` contains your main class. Getdown just builds a classpath based on the contents of `getdown.txt` and then runs Java with the main class you specify (also in `getdown.txt`).
