### ISSUE TITLE
Add task to download all jar files from remote appbase to local machine

### ISSUE THREAD

**Issue by hellboy81** [threerings/getdown#132]
I am now migrating jnlp to getdown. Having trouble with generating digest. Need to get from remote server 500+ jars. All jars are listed in getdown.

Please provide [debug] task to download  from remote to local machine to make generating digest possible.

**Comment by samskivert** [comment]
It's not even clear what build system you're talking about, but this is not something that Getdown would handle. If you need to download files as part of your build, there are Maven or Gradle plugins to handle it, or you can figure out some other solution.

**Comment by hellboy81** [comment]
> If you need to download files as part of your build, there are Maven or Gradle plugins to handle it, or you can figure out some other solution.

This is build I don't own.

I have security trouble with JWS after installing JRE j2se 1.8.0_181

**Application Blocked by Deployment Rule Set**

For security, applications must now meet the requirements for the High or Very High security settings, or be part of the Exception Site List, to be allowed to run.

[More:](https://java.com/de/download/help/jcp_security.xml)

Deployment Rule Set required Java version 1.8.0_60 is not available or incompatible with version 1.8+ requested by the Application.

Due on some  restriction I cannot change It is not possible to add url to Exception Site List (button Add is disabled).

I need to write test automation script which should download and start java applications on CI (Jenkins) with **endurance**. 

At the moment legacy JWS deployment architecture is used.

I have access only to jnlp file and deployed Java Web Start jar files on server.

Is there possible to upgrade this legacy deployment mechanism to `getdown` workflow?
