### ISSUE TITLE
Add support for pack200

### ISSUE THREAD

**Issue by neher** [threerings/getdown#14]
Pack200, specified in JSR 200, is a compacting archive format developed by Sun, reducing JAR file sizes by a factor of 7 to 9.

It would be nice if getdown supports pack200 files and unpacks them after downloading.
This will reduce the download time of big jar files.

**Comment by renato** [comment]
Are you going to support Pack200? That would be a great improvement.

**Comment by samskivert** [comment]
Just merged the commit that adds that support.

**Comment by neher** [comment]
Woohoo!
