### ISSUE TITLE
Get down works with openjdk?

### ISSUE THREAD

**Issue by sreerama-naga** [threerings/getdown#144]
Does Get down works with Openjdk?
Or
It works only with oracle jdk?

**Comment by samskivert** [comment]
Getdown should work with OpenJDK. It does not, as far as I know, use any of the proprietary APIs exclusive to the Oracle JDK. That said, this question would be better posed to the Getdown discussion group, where people who have _actually used_ Getdown with OpenJDK might be able to provide more concrete information.

Issues are for reporting bugs in the Getdown code, and there is only one person reading the issues (me), and I have not used Getdown to deploy a commercial application in ten years.
