### ISSUE TITLE
Proxy password

### ISSUE THREAD

**Issue by throth** [threerings/getdown#147]
Is there a way to enter a proxy password?
The proxy dialog currently allows only to enter host and port.

Thanks.

**Comment by samskivert** [comment]
There is currently no way to enter a proxy password. Getdown stores the proxy host and port information in plain text in a file in the appdir, which would not be a viable solution for maintaining the password for an HTTP proxy.

We could potentially not store the proxy password and simply require that the user enter the proxy password _every time_ the app is started, but that seems like such a bad user experience that it's not even worth supporting.
