### ISSUE TITLE
Running getdown on servers with low limits

### ISSUE THREAD

**Issue by WPCleaner** [threerings/getdown#149]
Hi,

I have a problem trying to run getdown on a server shared by many people where resources are very limited, especially the number of threads authorized for each user.

When I try to run getdown for [WPCleaner](https://tools.wmflabs.org/wpcleaner/), I end up with an OutOfMemoryError and the message Unable to create new native thread from a call to ThreadPoolExecutor.execute() in data.Application.verifyResources().
I searched a bit on the net, and it seems it can be because the maximum number of threads is already reached.

I ran ulimit -u and the computer, the result is a maximum of 30 which is low.
The command nproc returns a value of 8, meaning 8 available processors.
In Application.java, the thread pool is created with Runtime.getRuntime().availableProcessors() which is a lot compared to the limit.

Is there a way to tell getdown not to use this number of threads ?

**Comment by samskivert** [comment]
I added a system property to configure this: `-Dthread_pool_size=N`. You pass that to the JVM running Getdown, like:

```
java -Dthread_pool_size=2 -jar getdown.jar appdir
```

I also changed the default to use the number of processors minus one instead of the full number of processors.
