### ISSUE TITLE
Compilation fails, apparently due to missing classpath files

### ISSUE THREAD

**Issue by dolda2000** [threerings/getdown#155]
I'm sorry if this is a trivial problem, as I have no experience with Maven, but when I see a build.xml I kind of assume that it should work with Ant. However, when trying to build the project with Ant, I get the following messages:
```
Buildfile: [...]/getdown/build.xml

-download-maven-ant:

-init-maven-ant:
[artifact:dependencies] There were no dependencies specified
[artifact:dependencies] There were no dependencies specified

-prepare:

compile:

BUILD FAILED
[...]/getdown/build.xml:55: [...]/getdown/src/main/resources does not exist.
```
A cursory look at the build.xml appears to indicate that it's looking for the files `compile.classpath` and `testlibs.classpath` for the "dependencies" that were supposed to be "specified", but these files are nowhere to be found in the project structure.

Is the presence of build.xml a mere ruse, which I should ignore and move on from Ant?

**Comment by samskivert** [comment]
Yeah, sorry. That's ancient cruft. Only way to build now is via Maven.
