### ISSUE TITLE
Interest for Pull Request: OAuth 2.0 & OpenID Connect authentication

### ISSUE THREAD

**Issue by ChristianCiach** [threerings/getdown#156]
HI!

I am currently evaluating Getdown as a replacement for Java Webstart for our corporation. It seems to work fine so far, but there is a crucial feature missing for us: Getdown doesn't support any kind of authentication mechanism when downloading the client application.

I am interested in adding such a feature. We are using OpenID Connect (a superset of OAuth 2.0), but when adding support for it to Getdown I will take care to do it in such a way that other authentication machanisms (like Basic Auth) can be added later.

To be specific, I want to implement the "Authorization Grant Flow" (with PKCE) described here: https://tools.ietf.org/html/rfc8252
This means Getdown-launcher should be extended to support these steps:

1. Add a configuration option to getdown.txt to enable/configure authentication.
2. When launching the Getdown-launcher it launches a webbrowser pointing to the authentication-endpoint of the Identity Provider, where the user can enter their credentials. At the same time, Getdown-launcher starts a mini-server on a random non-priviledged port.
3. When the user has entered valid credentials, the Identity Provider redirects the website to http://localhost:[port of Getdown] and passes the authentication code.
4. Getdown-launcher retrieves the authentication code and stops the mini-server. It then uses this code to retrieve the access- and refresh-tokens from the /token-endpoint of the Identity Provider.
5. Getdown-launcher uses the access-token to successfully download the protected jar-files and other files by using the access-token for the "Authentication" HTTP-header. 
6. Optionally, Getdown-launcher passes the access- and refresh-tokens to the launched client application.

As we would rather not maintain our own local fork of Getdown in the long run, I want to ask if there is interest in a Pull Request like this or if you think this feature is out of scope of Getdown.

**Comment by samskivert** [comment]
Apologies for the delay in responding.

I am on board with having support for this in Getdown, as it opens the door to a variety of use cases at fairly low complexity cost in the Getdown code and configuration. So I'm happy to review and merge pull requests along these lines.

**Comment by ChristianCiach** [comment]
Thanks for the answer! I will consider the next steps carefully and may come back to you later.
