### ISSUE TITLE
Option to force creation of appdir directory if it doesn't exist

### ISSUE THREAD

**Issue by maeichris** [threerings/getdown#163]
This is related to Issue #87, but with different requirements and therefore a different suggested feature.  I'd like to create an installer that installs the following files in the following locations:

Program Files:
- getdown-launcher-1.8.0.jar
- uninstaller.exe

(All Users) Start Menu Programs
- A Shortcut to run getdown-launcher with parameters to start my application.  It uses -Dappbase so the getdown.txt does not have to be distributed in the installer.

The general approach is that the installer is only for the launcher.  The end-user runs the launcher portion which then downloads the actual end-application and runs it.  The beauty of this is that the user just needs the launcher installed on their machine, and then the end-application can be updated on the server at any time without running a new installer.  The only question is where to point `appdir` to.

In the (unlikely) scenario where two people are trying to launch at the same time, I thought it would be best to not have the `appdir` point to a shared location so the two users would not be downloading/overwriting files at the same time.  Unlike those in Issue #87, I wouldn't mind having multiple copies of the application on disk, as long as they are separated out in different user folders.  Therefore it would be nice to put it somewhere under %LOCALAPPDATA%.  However, the installer cannot create this folder for all users.

I currently have the shortcut pointing to a predefined location in the user's home folder.  However, the folder does not exist for the reasons mentioned above.  When running getdown-launcher, it complains with "Invalid appdir '%LOCALAPPDATA%\CompanyName\AppName'." (but with LOCALAPPDATA expanded).

The request therefore is:  I would like an option added on getdown-launcher to force creation of the `appdir` folder/directory if it does not exist.  Perhaps add a "-f" or "-c" no-arg command-line option.

FYI, my NSIS CreateShortcut command (with company-specific names and URLs changed) is:
```
  CreateShortcut "$SMPROGRAMS\CompanyName\AppName.lnk" "javaw" \
    `-Dappbase=https://hostName.com/appFolder/ -jar getdown-launcher-1.8.0.jar "%LOCALAPPDATA%\CompanyName\AppName"` \
    "" "" SW_SHOWNORMAL "" "App Name"
```

**Comment by maeichris** [comment]
Workaround:
Throw caution to the wind and set appdir to "%ALLUSERSPROFILE%\CompanyName\AppName", and use the NSIS AccessControl plugin to grant all users write access.  The risks of doing this are:
- more than one user on a Windows box at once overwriting files at the same time
- something putting something malicious in this common folder; it's not 100% clear to me under what conditions getdown would re-download the checksums from the actual server to make sure they are correct, or if it would blindly forge onward.

**Comment by HasseNasse** [comment]
Why was this issue closed?

**Comment by maeichris** [comment]
Take a look at the revision 469f4fe that samskivert closed this with.  It addresses the issue.  It has been there since release 1.8.1, if I'm reading the tags right.

His comment on the commit was:

**Auto-create app dir if we have an appbase.**

We were already doing this for bootstrap.properties-based launches, but there's
no reason to restrict it to that. If you run Getdown with an appbase and an
appdir, it can create the app dir and download the app into it.

This enables scenarios where getdown is installed to a shared location and
users that run the app install it in their private storage area (or on a
machine local file system, or who knows).
