### ISSUE TITLE
Concurrent downloads corrupted

### ISSUE THREAD

**Issue by vatsal22** [threerings/getdown#166]
I was testing the new concurrent downloads using the old streams impl and it looks like the resources are being corrupted on download. Getdown will try to download the files and check them but their digests won't match with the server-side files. After exhausting the 5 retries, it throws the "m.unable_to_repair" error. Each time it seems to be unable to download a random few set of files. 

I tried manually computing the hashes of some of the files that Getdown couldn't resolve and they really are corrupted somehow. It probably has something to do with how each thread actually writes the files to disk in HTTPDownloader because flipping the implementation to use the Channels impl works fine (besides the wonky progress bar).

I don't know if it's an issue with just our application or not (we tested it on multiple computers and servers), but for now I'd recommend changing the default for max_concurrent_downloads from 2 to 1. Additionally, maybe make Getdown use the Channels impl if max_concurrent_downloads>1? 

Besides the temporary fixes mentioned above, I really have no idea what might be causing this corruption using the streams.

**Comment by samskivert** [comment]
Hrm. Is it reporting an actual error when trying to download these broken resources? Or does it claim to complete successfully but the files are still corrupted?

And the problem goes away if you set max_concurrent_downloads to 1 (but still use the HTTPDownloader)?

**Comment by vatsal22** [comment]
It reports an actual error when trying to download them. The UI ends up saying: "We were unable to download the necessary files after five attempts..."

The cycle for these problematic files is: download -> try to validate -> fail validation -> redownload  (x5)

And yes, it goes away if you set max_concurrent_downloads=1 but still use the streams impl

**Comment by samskivert** [comment]
What about in launcher.log? Does it say: `Download failed [rsrc=...]` with an exception?

I'm trying to figure out if an error occurs during the download process which then naturally results in validation failure, or if no error occurs during the download process, but the downloaded data is still invalid and fails validation.

**Comment by vatsal22** [comment]
INFO Failed to load digest: [homedir]\digest2.txt (The system cannot find the file specified). Attempting recovery...
INFO Attempting to refetch 'digest.txt' from '[host]/[app]/digest.txt'.
..........................(some more predownload stuff)..................
INFO Unversioned digest changed. Revalidating...
INFO Resource failed digest check [rsrc=[resource1], error=java.io.FileNotFoundException: [homedir]/[resource1] (The system cannot find the file specified)]
........................(the above repeats for all the other resources) .........................
INFO 57 of 57 rsrcs require update (0 assumed valid).
......................(here all the files seem to download without error) .............................
INFO Resource failed digest check [rsrc=[resource2], error=java.util.zip.ZipException: invalid CEN header (bad signature)]
.......................(This error continues for 45 more resources. Only 11 passed this run of verification tests)...........

The following consists of Getdown redownloading those 45 corrupted resources, then a portion of these new downloads fail their verifications. This continues 5 times until this shows up:


WARNING Pants! We couldn't get the job done.
WARNING getdown() failed. [java.io.IOException: m.unable_to_repair=<toString() failure: java.lang.ArrayIndexOutOfBoundsException: 1>]
java.io.IOException: m.unable_to_repair
	at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
INFO Releasing lock


All in all it downloaded half of the required files uncorrupted

**Comment by samskivert** [comment]
OK, I found the problem. Yet another single-threaded assumption overlooked when converting to multi-threading. Such changes are never simple! :) I'll do another release to get this fix out there.
