### ISSUE TITLE
Support forcing validation of downloaded resources

### ISSUE THREAD

**Issue by austin-bowen-iss** [threerings/getdown#187]
First of all, thank you for all the work you have put into this project, it's really been a life saver in our effort to move away from JWS!  We've just run into one issue:

I understand that Getdown creates *v files for each validated resource so that it does not have to re-validate the resources before every launch, but we have found that this opens up the possibility that a client could modify a downloaded and validated resource (e.g. modify a class in a jar file), which Getdown will happily not verify if that *v file is in place.

Could you add a Getdown config option to force validation of all resources before _every_ launch?  That way, if the user tampers with any downloaded resources, it will be redownloaded and revalidated before launch?

Again, I understand the motivation behind the *v files.  But our company would really like for Getdown to have the option to revalidate all resources before every launch.  We're going to have to resort to pre-deleting the *v files before running Getdown in order to get around this vulnerability.

**Comment by samskivert** [comment]
I added `revalidate_policy` to enable this use case. Check the docs:

https://github.com/threerings/getdown/wiki/Getdown-Dot-Text#revalidate_policy
