### ISSUE TITLE
Convert getdown.txt to getdown.xml

### ISSUE THREAD

**Issue by agharta** [threerings/getdown#2]
Hi,
My compliments to your project, it solved me many problems!!!

One tip: what do you think about convert getdown.txt into a more standard and flexible xml???

In this way, you can include an xls/dtd for code-completion&validation!

Thanks a lot again for your fantastic work!

Agharta

**Comment by BrianKnoblauch** [comment]
Perhaps make it optional.  I prefer the text config myself.

**Comment by noblemaster** [comment]
I prefer the .txt configuration file also.

**Comment by gravelld** [comment]
I'd prefer a .conf file ;-)
