### ISSUE TITLE
Can getdown update contents of a zip or jar ?

### ISSUE THREAD

**Issue by Ali-RS** [threerings/getdown#201]
Hi 
I am new to getdown
I am creating an online game, it has a big asset.jar (I can also use it as a asset.zip file which can be loaded using AssetManager of game engine using a ZipLocator). This file contains all the game assets. 
I want to know If I change/add some new files to asset.jar/asset.zip at server, can getdown update only modified/added files at client side without re-downloading whole asset.jar/asset.zip  ? 

Thanks

**Comment by Ali-RS** [comment]
It seems patch files using jardiff is what I am needing. 
Looking at documentation I could find [Generating patch-files for faster updates](https://github.com/threerings/getdown/wiki/Version-Patches) but the page is empty. Will appreciate if someone can link to some tests case and any documentation. 
Thanks

**Comment by samskivert** [comment]
This is actually documented on the "versioned mode" page:

https://github.com/threerings/getdown/wiki/Versioned-Mode

Look at the section in there on patch files.

**Comment by Ali-RS** [comment]
Thanks
