### ISSUE TITLE
No break condition in download file loop

### ISSUE THREAD

**Issue by frydaykg** [threerings/getdown#205]
I didn't found any break statement in cycle where is dowload of file is going:
https://github.com/threerings/getdown/blob/388ba71ec0c1af5c198daf8158db494c333b6bfb/launcher/src/main/java/com/threerings/getdown/launcher/Getdown.java#L317

That's why file is downloading 5 times and sometimes ti leads to corrupted file.

**Comment by samskivert** [comment]
The very last statement in that for loop is a `return`. If it reaches that, it means that the app was succesfully updated and launched, and the loop stops. It only loops back if something goes wrong and it needs to start the update process again from the beginning.
