### ISSUE TITLE
proxy authentication -  understanding of workflow

### ISSUE THREAD

**Issue by wumpz** [threerings/getdown#216]
We want to use the new proxy authentication possibility of getdown 1.8.3.

The problem is, that getdown does download our application artifacts from our servers using the configured proxy with its authentication. But our application itself needs this proxy authentication / configuration as well. GetDown somehow does not send proxy settings to our application.  How to achieve this? GetDown starts the application within a new process.

**Comment by samskivert** [comment]
As you have presumably discovered, Getdown passes the proxy info on to the app via the `http.proxyHost` etc. system properties. Hopefully this addresses your issue. If not, feel free to comment and reopen this issue.
