### ISSUE TITLE
Startup-Error with --add-opens Parameter in extra.txt

### ISSUE THREAD

**Issue by cstsw** [threerings/getdown#237]
We use getdown to launch a swing-application currently ported to Java 11. In order to avoid "Illegal reflective access" warnings for our users we like to spend some `--add-opens` parameters.

When we place them in `extra.txt` getdown is not able to launch our program. `The launcher.log` says:

```
2019/10/14 11:10:37:270 INFORMATION Running <Path to>\openjdk-11.0.4+11-jre\bin\javaw.exe
  -classpath
  <a lot of jars>
  -Dcom.threerings.getdown=true
  -Xms50m
  -Xmx300m
  --add-opens java.desktop/javax.swing=ALL-UNNAMED
  --add-opens java.base/java.lang=ALL-UNNAMED
  <a lot of Sytemproperties (-D...=...) from extra.txt>
  <Class containing the main method>
Unrecognized option: --add-opens java.desktop/javax.swing=ALL-UNNAMED
```

(Everything between `-Dcom.threerings.getdown=true` and our Main-Class is from extra.txt.)

However, if I run `javaw` manually with the exact parameters from `launcher.log`, the JVM is able to start.

My questions are:
- What could be the difference between launching the program manually and via getdown that leads to the JVM startup error?
- Is extra.txt a valid place to add parameters like `--add-opens`?
- Are Java 9++ parameters already supported by getdown/via `extra.txt`?

In addition to or instead of solving this problem, it would be helpful if the wiki-documentation would include `extra.txt` (what can be achieved by it, how and where are it's contents placed in the java-call to launch the user-application, which JVM-parameters are allowed/disallowed in `extra.txt`. etc.).

**Comment by samskivert** [comment]
Each line of `extra.txt` is passed as a single argument when launching java, so anything that would be separated by a space on the command line has to be on a separate line in extra.txt. Getdown does not break arguments on spaces because then it would have to handle quoted arguments and reimplement half of what the shell does.

Try putting:

```
--add-opens
java.desktop/javax.swing=ALL-UNNAMED
--add-opens
java.base/java.lang=ALL-UNNAMED
```

in your extra.txt and it should hopefully work.

**Comment by samskivert** [comment]
Feel free to reopen this issue if that doesn't fix it.

**Comment by cstsw** [comment]
Thanks for the advice, @samskivert. Splitting the parameters and values into individual lines indeed solves the problem for me and I fully understand the rationale behind it.

Again, it would be nice if `extra.txt` and how it's contents are passed to the java call could be documented.
