### ISSUE TITLE
Updating custom jvm from 8 to 13 breaks jvm

### ISSUE THREAD

**Issue by bskaarup** [threerings/getdown#238]
When moving from Java 8 to 13 (on Windows) I have found an issue that possible should be adressed.
Getdown does not clean the java_vm folder first, but perhaps it should.
In Java 8 there are 10 folders inside the lib folder. One is called "ext" (that is not present in Java 13) and it seems that the "ext" cannot coexits with Java 13. If the folder is present (even if it is empty) Java Virtual Machine Launcher crashes at startup with the message "Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit"
Deleting the folder, makes the jvm work.

The workaround I have found is to put the new jvm in a new folder (not java_vm) and set java_local_dir in getdown.txt
We use Oracle Java 8u201 and AdoptOpenJDK 13.1

**Comment by Adrodoc** [comment]
I think this is a duplicate of #112.

**Comment by bskaarup** [comment]
Fixed with https://github.com/threerings/getdown/pull/257
