### ISSUE TITLE
Unable to hide decorations from launch window

### ISSUE THREAD

**Issue by Bartimmermans** [threerings/getdown#26]
I am trying to hide the decorations from the launch window by using `ui.hide_decorations=true`. However, my window is still decorated, showing the name and icons.

I can't find out what I am doing wrong.

Please find below my configuration:

> # ui configuration
> 
> ui.name = Skybridge
> ui.background = FFFFFF
> ui.background_image = images/skybridge_splashscreen.jpg
> ui.progress = 0, 388, 650, 30
> ui.progress_bar = EBB80F
> ui.progress_text = 004E72
> ui.status = 16, 366, 300, 8
> ui.status_text = 004E72
> ui.icon = icons/unifly_color_icon16.png
> ui.hide_decorations = true

**Comment by neher** [comment]
Seems to work with latest version development version.
The functionality was only added with commit https://github.com/threerings/getdown/commit/3c32a119e8fca359cc0d1e12346875b669b2ff82 , which is not part of a release yet.

**Comment by Bartimmermans** [comment]
Ok thanks. I will try it out.

**Comment by Bartimmermans** [comment]
Works nice. Thanks.
