### ISSUE TITLE
Getdown.txt in relation to the operating system

### ISSUE THREAD

**Issue by borgogelli** [threerings/getdown#32]
Hello

we have developped a multi-platform app and we have a problem configuring java option on the getdown.txt file, because java options have different syntax on different operating systems
For example on windows the path separator is the semicolon char (**;**) while on Linux is the colon char (**:**)

So on Windows our getdonw.txt configuration contains
  jvmarg = -Djava.library.path=folder1**;**folder2
while on Linux 
  jvmarg = -Djava.library.path=folder1**:**folder2

> (please read carefully, the above statements are different, the first contains a semicolon and the second a colon)

Future versions of the program should take this into account.
It would be interesting to provide different java configurations, in relation to the user operating system.

What about that ?

Regards from Italy

Andrea

**Comment by samskivert** [comment]
Getdown already supports this: https://github.com/threerings/getdown/wiki/Getdown-Dot-Text#platform-specific-configuration

Just use:
```
jvmarg = [windows] -Djava.library.path=folder1;folder2
jvmarg = [!windows] -Djava.library.path=folder1:folder2
```
