### ISSUE TITLE
Classpath needs to be customizable

### ISSUE THREAD

**Issue by beirtipol** [threerings/getdown#38]
My app suffers from having a very long classpath (16k characters at last count). Because of this I create a custom-classpath.jar containing the classpath in the manifest. I then put this classpath.jar as the classpath when launching my app. I can't see a way to configure this in the getdown.txt

The end result is that the app cannot launch because it the command line is too long (Windows limits to 8192 chars)

**Comment by samskivert** [comment]
This should be addressed by 4fd707d54dcab200a68a65d4e81379992abec4db which allows you to create one jar with a main-class header and a class-path header which will be used automatically because Getdown will launch your app as "java -jar custom-classpath.jar".

**Comment by beirtipol** [comment]
Hi, sorry for the delay in responding. This doesn't quite address the issue. I need to be able to specify the classpath jar as well as the startup class.
