### ISSUE TITLE
Launch the application as a jar file

### ISSUE THREAD

**Issue by ihommani** [threerings/getdown#42]
Hi, 

I am willing to launch the application through getdown as a jar file. 
e.g:  'java -jar foo.jar'

However the current behavior of getdown is to launch the application by specifying the classpath. 
'java -classpath foo.jar'
In the case the jar represents a web app that relies on dependencies packaged inside the same jar, we have exception such as NoClassDefFound. 
On the contrary, launching 'java -jar foo.jar' perfectly works.

So here my questions: 

1. Am I missing something in the getdown dot text that can tackle my need ?

2. Is getdown considering the "jar option" in its roadmap ?

3. If so, I can make a pull request since I already implemented my need in a fork.  

Thx for your help

**Comment by samskivert** [comment]
It's not on the roadmap, but it's certainly something I'm happy to support. If you want to send a pull request, feel free, otherwise I can add it super easily.

**Comment by samskivert** [comment]
I went ahead and added support for this. See 4fd707d54dcab200a68a65d4e81379992abec4db and also the new docs in the Getdown-Dot-Text section of the wiki.

**Comment by ihommani** [comment]
Thank you very much for the update.
