### ISSUE TITLE
Verification file still here after application launch

### ISSUE THREAD

**Issue by ihommani** [threerings/getdown#43]
Hi, 

I would like to know if it is normal that we still have validation files after the application  (code) startup.

If so, can we consider to remove them  ?
According the doc (https://github.com/threerings/getdown/wiki/Design#validation-path) those files tells Getdown that the tracked file has been checked. 
So once the application is launch we don't need them anymore, right ?

Seems like the 'clearValidationMarkers' can do the work but i'm not sure about the consequences.

**Comment by samskivert** [comment]
Those stay around between invocations of your app because Getdown uses their existence to avoid doing the (very expensive) full hash validation of all of your resources every time your app launches.
