### ISSUE TITLE
Create the proxy.txt when needed

### ISSUE THREAD

**Issue by ihommani** [threerings/getdown#44]
Hi, 

Using getdown, I observe the creation of the file proxy.txt. 
Is it mandatory ? Can we condition this creation on the content of getdown.txt ?

Thx

**Comment by samskivert** [comment]
The reason that gets created is that Getdown tries to auto-detect whether the user's system has a proxy configured and if it detects that it does not, it writes that file to avoid doing the detection again in the future.

Unfortunately the detection is complicated enough that it's worth the extra trouble to make a note that we don't want to do it again in the future.

We could have a getdown.txt configuration that disables proxies entirely, but then your app might not run on systems that need proxy configuration...

**Comment by ihommani** [comment]
thx for the answer.
