### ISSUE TITLE
Expose in the getdown console the output of the launched process 

### ISSUE THREAD

**Issue by ihommani** [threerings/getdown#45]
Hi, 

Last version of getdown allows to launch a 'jar' application with the "manifest" keyword. (class = manifest)
However the wiki states that  it is not possible to use the flag "-Ddirect=true" with this option.

Launching the app in the same jvm than getdown would be interesting to directly get the application's output in the same console used to launch the update of the said app.(instead of tailing the log file)

Do you think this would be easy to achieve ?

Thx

**Comment by samskivert** [comment]
There would be no reason to use `java -jar` with `-Ddirect=true`. Getdown already does everything that `java -jar` does, so just use Getdown normally in that case. If you use `-Ddirect=true` then Getdown is going to build the classpath in memory, not via a command line, so the need to use a manifest with `Class-Path` to avoid exceeding command line length limits goes away. Getdown's `class` is equivalent to a Jar manifest's `Main-Class`.

So it's not clear what purpose this would serve other than to duplicate a bunch of complicated code.

**Comment by ihommani** [comment]
Hi, 

Maybe I misunderstood the use of 'Ddirect'. What I would like, would be to output the launched  application's stdout in the console I openned to update the application through getdown.

e.g: I launch
`java -jar getddown myApp`

The update occurs, and then I get the prompt. Is it possible to get the myApp's output in the same terminal used to call getdown ?

**Comment by samskivert** [comment]
Getdown works very hard to _avoid_ sending output to the console, because the normal launch of an application on a normal users machine does not happen from the command line. It happens by double clicking an icon somewhere and if that resulted in a terminal popping up spewing arcane text at the user, that wouldn't be a very good user experience.

However, if you are just debugging or for some reason you really want your users to launch your app from the console, then you can most likely achieve what you want with the following:

```
java -Ddirect=true -Dno_log_redir=true -jar getdown.jar myapp
```

**Comment by ihommani** [comment]
Ok, thx for the explanation.

**Comment by ihommani** [comment]
But, using -Ddirect=true is not possible with the "jar mode", right ?

> It is also not possible to use this mode if you are using -Ddirect=true to launch your application in the same JVM in which Getdown is running.

**Comment by samskivert** [comment]
Correct, but there's no reason to use jar mode if you're using -Ddirect=true.

**Comment by ihommani** [comment]
Yes, I see the point. However in my specific case launching the jar application allows me to directly get the log of the application in the console.
Instead of openning or tailing the log file, I directly get the status in the console. 
But I understand this need can be too much specific.

**Comment by samskivert** [comment]
Whether app output goes to the console has nothing to do with using `java -jar`. If you use `-Ddirect=true` then app output goes to wherever Getdown output goes, and if you use `-Dno_log_redir=true` then Getdown (and your app) output goes to the console.

**Comment by ihommani** [comment]
Ok, I get it.
Thanks for the explanation.
