### ISSUE TITLE
Cache overwrite issues.

### ISSUE THREAD

**Issue by BrianKnoblauch** [threerings/getdown#47]
I've noticed that the cache gets overwritten during updates and causes already running instances to have faults.  To duplicate:

- Start the first instance of a getdown launched application
- Update the application on the web server
- Start a second instance of the application

The new code will be pulled down and overwrite the locally running (cached) version.  This will cause anything from lockups to random behaviors in the instances that were running before the update.

**Comment by samskivert** [comment]
Getdown is not designed to support multiple running instances of the same application.

**Comment by thokuest** [comment]
@BrianKnoblauch Maybe you're interested in #69.
