### ISSUE TITLE
No Java Flight Recordings when started with GetDown

### ISSUE THREAD

**Issue by MystyxMac** [threerings/getdown#49]
I want to profile with Java Flight Recorder / Java Mission Control, so I put the appropiate jvmargs in the getdown.txt. When I open the recording file, I keep getting the a message that says that there are no recording events.
Strangely when I start my progam without GetDown, I do get a working recording.

Any idea why this is (not) happening?

Edit: Added jmvargs
BTW I'm using the latest which has the %ENV.XXX% feature.
**From getdown.txt**

```
# Java VM Args
jvmarg = -Xms512m
jvmarg = -Xmx512m
jvmarg = -Dsun.java2d.d3d=false
jvmarg = -Dsun.java2d.ddoffscreen=true
jvmarg = -Dsun.java2d.noddraw=true
jvmarg = -XX:+UnlockCommercialFeatures
jvmarg = -XX:+FlightRecorder
jvmarg = -XX:FlightRecorderOptions=disk=true,repository=<path>\%ENV.USERNAME%,dumponexit=true,dumponexitpath=<path>\%ENV.USERNAME%
jvmarg = -XX:StartFlightRecording=defaultrecording=true,settings=profile
```

**From launcher.log**

```
-Xms512m
-Xmx512m
-Dsun.java2d.d3d=false
-Dsun.java2d.ddoffscreen=true
-Dsun.java2d.noddraw=true
-XX:+UnlockCommercialFeatures
-XX:+FlightRecorder
-XX:FlightRecorderOptions=disk=true,repository=<path>\%ENV.USERNAME%,dumponexit=true,dumponexitpath=<path>\%ENV.USERNAME%
-XX:StartFlightRecording=defaultrecording=true,settings=profile
```

Looks pretty the same to me...

**Comment by samskivert** [comment]
Can you include the part of your getdown.txt that sets the jvmargs?

Also, Getdown generates a launcher.log (in the app directory) which will tell you exactly what arguments it's passing to the JVM when it launches your app, so you can look at that to see if something looks amiss.

**Comment by MystyxMac** [comment]
I modified my first post with the requested info.

**Comment by samskivert** [comment]
Those backslashes are preventing the %ENV.USERNAME% blocks from working. In the launcher.log you should not see %ENV.USERNAME% you should see the actual environment  variables that were substituted.

For example, if I add this to the Getdown testapp:

```
jvmarg = -Dusername=%ENV.USER%
```

When I look at launcher.log I see my actual USER env variable:

```
2016/03/23 09:11:01:988 INFO n.a: Running /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/bin/java
  -classpath
  /Users/mdb/projects/getdown/testapp/target/testapp/testapp-jar-with-dependencies.jar
  -Xdock:icon=/Users/mdb/projects/getdown/testapp/target/testapp/../desktop.icns
  -Xdock:name=Getdown Test App
  -Dcom.threerings.getdown=true
**  -Dusername=mdb
**  com.threerings.testapp.TestApp
  /Users/mdb/projects/getdown/testapp/target/testapp
```

**Comment by samskivert** [comment]
Oh, actually it's probably not the backslashes. I just tried that, and it still did the substitution:

```
jvmarg = -Dusername=\%ENV.USER%
```

yielded:

```
  -Dusername=\mdb
```

So you must just not actually be using the new code.

**Comment by MystyxMac** [comment]
I'm using the new code. The problem is not the substitution of the ENV parameters.
When I start my app with getdown, it creates a folder like c:\data\app\mystyxmac. The recording files also gets created, but when I try to open it in Mission Control, I get the message that there are no recording events.
When I start my app without getdown, there are recording events.

**Comment by samskivert** [comment]
I don't know. Getdown reports in launcher.log the EXACT command line that it is running. So if you run that exact same command and get different behavior, then something outside of Getdown's control is going awry.
