### ISSUE TITLE
Display an accurate message to the user on "no nospace left" exception

### ISSUE THREAD

**Issue by reda-alaoui** [threerings/getdown#58]
Hello,

When there is no more disk space while getdown is downloading app components, we end up with the following kind of stack trace:

``` java
2015/11/24 12:15:16:605 INFOS n.a: Downloading resource [url=http://localhost:9000/my-lib.jar.pack.gz, size=85085]
2015/11/24 12:15:16:621 AVERTISSEMENT n.a: Download failed [rsrc=null]
java.io.FileNotFoundException: .\lib\my-lib.jar.pack.gz (Espace insuffisant sur le disque)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at com.threerings.getdown.net.HTTPDownloader.doDownload(Unknown Source)
    at com.threerings.getdown.net.Downloader.download(Unknown Source)
    at com.threerings.getdown.net.Downloader.download(Unknown Source)
    at com.threerings.getdown.launcher.Getdown.download(Unknown Source)
    at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
    at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
```

Would it be possible, on FileNotFoundException catch, to check for the disk space and display an accurate message to the final user?
Or maybe we could just display the technical error which is sufficiently understadable?

In any case, I think the exception should be catched and not trigger a Getdown crash.

**Comment by samskivert** [comment]
I agree that it would be great to handle full disk more gracefully. But does it really cause Getdown to crash? Does Getdown not display an error dialog saying that the download failed? I know that it doesn't say _why_ it failed, which would be good and maybe we can fix, but I believe that at least does something and doesn't just crash.

**Comment by samskivert** [comment]
It looks like this code is run when the download fails:

```java
            public void downloadFailed (Resource rsrc, Exception e) {
                updateStatus(MessageUtil.tcompose("m.failure", e.getMessage()));
                log.warning("Download failed", "rsrc", rsrc, e);
            }
```

That code already takes the message supplied by the Java exception ("Espace insuffisant sur le disque" in your case) and composes it into a large error message specified by m.failure, in French it looks like it is:

```
\u00c9chec du t\u00e9l\u00e9chargement: {0}
```

where the Java error message is put into `{0}`. Is this not sufficient?
