### ISSUE TITLE
Webstart "Sandbox"

### ISSUE THREAD

**Issue by ruckc** [threerings/getdown#61]
Is there any intention of providing Sandbox support through Java's Security Manager?  Part of the theoretical (though often times more questionable) value of WebStart was the Sandbox.

**Comment by samskivert** [comment]
No. Getdown's main aim is to be an installer for "desktop" (fully privileged) apps, not to take on the substantial complexity of trying to run sandboxed apps.

You can still sign your app and provide it with a security policy to allow it to load untrusted code using Java's sandbox mechanisms, but Getdown's job in that scenario is to run your trusted code which then hosts its own sandbox.
