### ISSUE TITLE
Resource Partially Updated

### ISSUE THREAD

**Issue by vibhay7** [threerings/getdown#62]
Whenever I am releasing any update, most of the clients are getting NoClassDefFound exception. I want to know are you deleting main resource file then start downloading, or you download file in temp folder then update original files ?

**Comment by jlanawalt** [comment]
I haven't looked into this but pull request #60 suggests that currently files are directly replaced.

**Comment by vibhay7** [comment]
Files should be downloaded in temp folder first. Merge this fix by runiter in the master

**Comment by runiter** [comment]
Not sure why my fix is not merged yet :(
