### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by thokuest** [threerings/getdown#63]
We're using Java Web Start currently to deploy our application. I'd like to bundle a JRE with the application and so I'm evaluating `getdown` as a replacement for the Web Start solution. So, first of all, thanks for this nice library. It works quite well.

Is the `getdown` project still active and accepts pull requests?

**Comment by samskivert** [comment]
It's still alive. It's a very mature project, so it doesn't change much, but I will get around to those two pending pull requests at some point.

**Comment by thokuest** [comment]
Thanks, that sounds great! I had pull request #60 in mind when I asked for the project's status.

**Comment by allanpro** [comment]
We followed this project for 3-4 years now and have been using it as a Java Web Start replacement.
