### ISSUE TITLE
First time JVM download does not unpack the JVM with getdown 1.6

### ISSUE THREAD

**Issue by janhurst** [threerings/getdown#78]
Hi,

I'm running into an issue where getdown 1.6 can't seem to unpack a downloaded JVM.

I've traced through the getdown code and it looks to me like a "bug" in the Resource.unpack() method.
I say "bug" because the code looks ok to me, just the behaviour seems to not be the intention.

I am piecing this together through the log and working through the code as it is a bit tricky for me to break into the running JVM.

I think I am reaching Getdown.updateJava() line 645 before an exception is thrown. I can see that the HttpDownloader is pulling down the JVM package into a local file named java_vm.jar_new, yet the Resource.unpack() method is trying to unpack java_vm.jar

It looks like the Resource.unpack() line 262 is (part of) the problem. Which is currently:

`return FileUtil.unpackJar(new JarFile(_local), _unpacked);`

With any downloaded resource I was expecting something like:

`return FileUtil.unpackJar(new JarFile(_localNew), _unpacked);`

Unfortunately I don't have easy access to Maven to rebuild a custom .jar right now.
Am I on the right track?

The launcher.log is as follows:

2017/01/19 12:44:22:342 INFO n.a: ------------------ VM Info ------------------
2017/01/19 12:44:22:345 INFO n.a: -- OS Name: Windows 7
2017/01/19 12:44:22:345 INFO n.a: -- OS Arch: amd64
2017/01/19 12:44:22:345 INFO n.a: -- OS Vers: 6.1
2017/01/19 12:44:22:345 INFO n.a: -- Java Vers: 1.8.0_92
2017/01/19 12:44:22:345 INFO n.a: -- Java Home: C:\Program Files\Java\jre1.8.0_92
2017/01/19 12:44:22:346 INFO n.a: -- User Name: <userid>
2017/01/19 12:44:22:346 INFO n.a: -- User Home: C:\Users\<userid>
2017/01/19 12:44:22:346 INFO n.a: -- Cur dir: C:\Jan\Code\Alice\build\getdown
2017/01/19 12:44:22:346 INFO n.a: ---------------------------------------------
2017/01/19 12:44:22:461 INFO n.a: Failed to find proxy settings in Windows registry [error=java.lang.UnsatisfiedLinkError: no jRegistryKey in java.library.path]
2017/01/19 12:44:22:465 INFO n.a: ---------------- Proxy Info -----------------
2017/01/19 12:44:22:465 INFO n.a: -- Proxy Host: null
2017/01/19 12:44:22:465 INFO n.a: -- Proxy Port: null
2017/01/19 12:44:22:465 INFO n.a: ---------------------------------------------
2017/01/19 12:44:22:496 INFO n.a: Able to lock for updates: true
2017/01/19 12:44:22:498 INFO n.a: Checking Java version [current=1080092, wantMin=1080102, wantMax=0]
2017/01/19 12:44:22:498 INFO n.a: Attempting to update Java VM...
2017/01/19 12:44:23:083 INFO n.a: Downloading 121028811 bytes...
2017/01/19 12:44:23:201 INFO n.a: Downloading resource [url=http://myhostname/.../jres/jre-1.8.0.102-windows-i586.jar, size=121028811]
2017/01/19 12:47:59:333 WARNING n.a: Failed to create JarFile from '.\app\java_vm.jar': java.io.FileNotFoundException: .\app\java_vm.jar (The system cannot find the file specified)
2017/01/19 12:47:59:333 WARNING n.a: getdown() failed.
java.io.IOException: m.java_unpack_failed
	at com.threerings.getdown.launcher.Getdown.updateJava(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
2017/01/19 12:47:59:335 INFO n.a: Releasing lock`

Note I have obscured some none essential details in the log above.

If I copy a successfully downloaded java_vm.jar_new as java_vm.jar and re-run getdown I do get further (getdown redownloads but uses the renamed file), and it looks like the JVM is unpacked ok. (see below... sadly I run into another issue which is completely unrelated and my fault in not setting up my project very well :))

<similar log as above without error followed by...>
2017/01/19 16:28:54:353 INFO n.a: Regenerating classes.jsa for .\app\java_vm\bin\javaw.exe...
2017/01/19 16:28:54:401 INFO n.a: Checking Java version [current=1080092, wantMin=1080102, wantMax=0]
2017/01/19 16:28:54:402 INFO n.a: Checking version of unpacked JVM [vers=1080102].

Regards,
Jan

**Comment by samskivert** [comment]
We accidentally broke this when we added support for downloading to the _new files and then installing over the current files once the download was successful. I just shipped a 1.6.2 release with the above fix.
