### ISSUE TITLE
Compile getdown.jar with debug symbols

### ISSUE THREAD

**Issue by gravelld** [threerings/getdown#80]
Is this possible? It's great the source is available, but without the line numbers debugging in an IDE becomes painful.

**Comment by gravelld** [comment]
Ok, I think I worked this out. In pom.xml, change the `obfuscate` parameter to false:
```
<obfuscate>false</obfuscate>
```
Then `mvn clean package` to recreate the JAR, and debugging (including remote debugging) should work with that.

**Comment by Adrodoc55** [comment]
This is an open source library so why are some of the classes obfuscated?
