### ISSUE TITLE
Reverted condition in buildClassPath 

### ISSUE THREAD

**Issue by bioscz** [threerings/getdown#81]
Hello, 
It seems that condition for creating Default or Cached ClassPath is reverted. With non or false parameter use_code_cache is created .cache directory and Cached ClassPath for launching:

public static ClassPath buildClassPath (Application app) throws IOException
{
        return app.useCodeCache() ? buildDefaultClassPath(app) : buildCachedClassPath(app);
}

Best regards
Jan Olsansky

**Comment by samskivert** [comment]
Whoops! You're absolutely right. I fixed it in 9e23a426a66199fb3c36100256933b36f7d7c60e.
