### ISSUE TITLE
use_code_cache doesn't work.

### ISSUE THREAD

**Issue by soapyfrog** [threerings/getdown#82]
If you set `use_code_cache` to `true` in getdown.txt you get an exception when trying to create the `Application`

Looking at https://github.com/threerings/getdown/blob/9e23a426a66199fb3c36100256933b36f7d7c60e/src/main/java/com/threerings/getdown/data/Application.java#L702

If `use_code_cache` is true it then tries to parse it a second time as an `Integer` which obviously fails with a NumberFormatException.

```java
        _useCodeCache = Boolean.parseBoolean((String) cdata.get("use_code_cache"));
        _codeCacheRetentionDays = cdata.containsKey("code_cache_retention_days") ?
            Integer.parseInt((String) cdata.get("use_code_cache")) : 7;
```

I suspect the `parseInt` is supposed to be on `code_cache_retention_days`.

**Comment by soapyfrog** [comment]
Thanks for quick fix. Any chance of a minor tag 1.6.3) with this and the recent "use cache logic" fix?

**Comment by samskivert** [comment]
Finally did the 1.6.3 release this morning, apologies for the delay.
