### ISSUE TITLE
Validation fails with uresource

### ISSUE THREAD

**Issue by Slohrsh** [threerings/getdown#88]
It seems that getdown downloads the resource to filesystem "tounpack.jar_new" and tries to unzip it (tounpack.jar) before it validates the file

getdown.txt:
[...]
uresource = ../XXX/XXX/tounpack.jar
[...]

[launcher.log](https://github.com/threerings/getdown/files/1453452/launcher.log)

**Comment by samskivert** [comment]
That got totally broken with the addition of the 'download to _new and install' process. I've updated the test app to test unpacked resources, so hopefully they'll remain working in the future. :)

I'll do a release with this fix shortly, but if you want to/can test the latest code before then to make sure it solves your problems I'd appreciate it.

**Comment by Slohrsh** [comment]
Now it works. Thanks :)
