### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by robeden** [threerings/getdown#90]
I recently started using Getdown and it's great (thanks for making it available!). One difficult thing, though, is that I have no idea of what's changed in releases. Would you consider keeping a changelog? (See [here](http://keepachangelog.com/en/1.0.0/) for a great approach.) It's light-weight in overhead and sure would help in knowing what to expect.

Alternatively, milestones could be used on issues... though that only catches changes relating to issues.

Thanks!

**Comment by borgogelli** [comment]
+1 It would be appreciable a migration path to the 1.7 from the 1.6 version.

**Comment by robeden** [comment]
Lovely. Thanks! 👍
