### ISSUE TITLE
Getdown Applet fails with m.corrupt_digest_signature_error

### ISSUE THREAD

**Issue by t0b1** [threerings/getdown#91]
It seems that Digester.signDigest uses "SHA1withRSA" to create digest.txt.sig (version 1) while Application.downloadControlFile verifies it using Digest.SIG_ALGO which is "SHA256withRSA".  That fails with a m.corrupt_digest_signature_error message on the client side (Java Applet).  Am I holding it wrong?  ;-)

**Comment by samskivert** [comment]
(Apologies for the slow reply.)

The intent is for anyone who is using the version of Getdown that supports digest2.txt to always ship a digest2.txt (and its associated digest2.txt.sig). Getdown tries to download and verify both digest.txt+digest.txt.sig and digest2.txt+digest2.txt.sig and as long as at least one of them succeeds, then it should proceed.

However, that code is kind of messy. It should know what version it is downloading and use the correct signature file for that version. So I'll fix that. But you should use digest2.txt if you can. The whole reason that we migrated from SHA1 to SHA256 is that SHA1 isn't terribly secure any more.
